[package]
name = "create_post"
version = "0.1.0"
authors = ["Ethan Wright <ethan@flareline.com>"]
edition = "2018"

[dependencies]
lambda_runtime = "0.2.1"
serde = "1.0.115"
serde_json = "1.0.57"
serde_derive = "1.0.115"
log = "0.4.11"
simple-error = "0.2.1"
simple_logger = "1.6.0"
