name: Deployment preparation
on:
  push:
    tags:
      - '**'
      - '!*test*'
jobs:
  build:
    runs-on: ubuntu-latest
    container: amazonlinux:latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v1
      - name: Install toolchain
        run: amazon-linux-extras install rust1=stable
      - name: Cache build output
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build in release mode and test
        run: cd src && cargo build --release --all-features && cargo test --release --all-features
      - name: Package up bootstrap into workflow artifact
        uses: actions/upload-artifact@v2
        with:
          name: Rust bootstrap
          path: target/release/bootstrap